#!/usr/bin/env node
import { describe, it } from 'node:test';
import { strict as assert } from 'node:assert';
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Iter 81 audit fix: pins documentation-vs-filesystem consistency.
 *
 * README.md and CLAUDE.md make structural claims — "code lives at X",
 * "see file Y", "the layout is Z". A future rename / move would
 * silently leave docs pointing at vanished paths. New contributors
 * read the README first; broken-link rot here is the worst onboarding
 * tax there is.
 *
 * Allow-list semantics: paths that are intentionally future-state
 * (created by a deploy script, generated by codegen, etc.) get an
 * explicit comment naming WHEN they come into existence.
 */

const FUTURE_STATE_PATHS = new Map([
  // Deploy script writes this on first contract deploy. Until then the
  // path is documented but doesn't exist. praetor-cli's load_address
  // creates the file when registering a contract address.
  ['deployments/arbitrum_sepolia.json', 'created by `praetor deploy` on first deploy'],
]);

function extractBacktickedPaths(text) {
  // Match backticked tokens that look like file paths (have at least one
  // slash or recognized extension). Filter generic word-only backticks
  // (e.g. `pnpm`, `bigint`) — we only care about path-shaped tokens.
  const re = /`([a-zA-Z][a-zA-Z0-9_\/.\-]+\.(?:sol|rs|ts|tsx|md|json|yaml|toml|mjs|js|html|graphql))`/g;
  const out = new Set();
  for (const m of text.matchAll(re)) {
    out.add(m[1]);
  }
  return [...out].sort();
}

async function readDoc(name) {
  return await readFile(resolve(REPO_ROOT, name), 'utf8');
}

describe('README.md — every backticked file path exists', () => {
  it('all README file-path references resolve on disk', async () => {
    const text = await readDoc('README.md');
    const paths = extractBacktickedPaths(text);
    assert.ok(paths.length > 0, 'README should reference at least one file path');
    const missing = paths.filter((p) => !existsSync(resolve(REPO_ROOT, p)) && !FUTURE_STATE_PATHS.has(p));
    assert.deepEqual(
      missing,
      [],
      `README references paths that do not exist on disk (or aren't in FUTURE_STATE_PATHS): ${missing.join(', ')}`,
    );
  });

  it('FUTURE_STATE_PATHS keys appear in README (anti-stale-allow-list check)', async () => {
    // If we allow-listed a future-state path, it MUST still be referenced
    // somewhere — otherwise it's stale and should be removed from the
    // allow-list (keeping the allow-list tight is the whole point).
    const text = await readDoc('README.md');
    for (const futurePath of FUTURE_STATE_PATHS.keys()) {
      assert.ok(
        text.includes(futurePath),
        `FUTURE_STATE_PATHS includes "${futurePath}" but README doesn't mention it — remove the allow-list entry`,
      );
    }
  });
});

describe('CLAUDE.md — every backticked file path exists', () => {
  it('all CLAUDE.md file-path references resolve on disk', async () => {
    const text = await readDoc('CLAUDE.md');
    const paths = extractBacktickedPaths(text);
    assert.ok(paths.length > 0);
    const missing = paths.filter((p) => !existsSync(resolve(REPO_ROOT, p)) && !FUTURE_STATE_PATHS.has(p));
    assert.deepEqual(
      missing,
      [],
      `CLAUDE.md references paths that do not exist: ${missing.join(', ')}`,
    );
  });
});

describe('README.md — repo layout ASCII tree directories all exist', () => {
  it('every directory line in the "Repo layout" tree resolves', async () => {
    const text = await readDoc('README.md');
    // Repo layout uses Unicode tree characters "├──". Each line names a
    // directory followed by "/" then optional comment.
    const re = /├──\s+([a-zA-Z][a-zA-Z0-9_\-]*)\//g;
    const claimed = new Set();
    for (const m of text.matchAll(re)) {
      claimed.add(m[1]);
    }
    assert.ok(claimed.size > 5, `expected several layout dirs, found ${claimed.size}`);

    // Each claimed directory must exist at SOME path in the repo. The
    // tree uses indentation to nest (e.g. plinth/ is under contracts/);
    // we can't easily reconstruct full paths from the ASCII tree alone,
    // so we just assert each name exists somewhere as a top-level OR
    // nested directory.
    const found = new Map();
    for (const name of claimed) {
      // Try common parent dirs.
      const candidates = [
        name,
        `apps/${name}`,
        `agents/${name}`,
        `services/${name}`,
        `contracts/${name}`,
      ];
      const hit = candidates.find((c) => existsSync(resolve(REPO_ROOT, c)));
      found.set(name, hit);
    }
    const missing = [...found.entries()].filter(([, hit]) => !hit).map(([n]) => n);
    assert.deepEqual(
      missing,
      [],
      `README layout claims directories that don't exist at any known parent: ${missing.join(', ')}`,
    );
  });
});

describe('CLAUDE.md — desing prototype HTML files exist', () => {
  it('both prototype HTML files exist (Prototype UI contract)', () => {
    // CLAUDE.md says "Study every HTML file in design/". The two specific
    // files referenced by name MUST exist or the UI scaffolding has no
    // source of truth.
    assert.ok(existsSync(resolve(REPO_ROOT, 'design/Atrium.html')));
    assert.ok(existsSync(resolve(REPO_ROOT, 'design/Atrium App.standalone.html')));
  });

  it('extracted tokens files exist (referenced by UI scaffolding)', () => {
    assert.ok(existsSync(resolve(REPO_ROOT, 'design/extracted/tokens.json')));
    assert.ok(existsSync(resolve(REPO_ROOT, 'design/extracted/full-render-tokens.json')));
  });
});

describe('CLAUDE.md — rules files exist', () => {
  it('every docs/conventions/*.md file referenced exists', () => {
    // CLAUDE.md "Detailed rules" table names 5 rule files. Each must exist.
    const rules = ['ui.md', 'testing.md', 'security.md', 'git.md', 'writing.md'];
    for (const rule of rules) {
      const p = `docs/conventions/${rule}`;
      assert.ok(
        existsSync(resolve(REPO_ROOT, p)),
        `CLAUDE.md references ${p} which doesn't exist`,
      );
    }
  });
});
